name: Run Code and Generate Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python main.py
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: path/to/your/report.file
